### ISSUE TITLE
Raw image data and ground truth

### ISSUE THREAD

**Issue by lebeli** [ironhide23586/RoomNet#1]
I would be interested in replicating RoomNet myself. Unfortunately the original dataset including the ground truth data for the unaltered images is not available anymore. Would it be possible to upload your dataset or send it to me directly?

**Comment by ironhide23586** [comment]
Hi @lebeli I noticed that the original dataset link isn't available. I've emailed you.

Thanks! :)

**Comment by lebeli** [comment]
Hi Mr. Biswas,

thank you so much for your response and the provided data :) Was this the
data hosted under http://lsun.cs.princeton.edu? Also I have read, that
there was a .mat file with keypoints as ground-truth. Do you have this as
well?

Am Do., 18. Juni 2020 um 11:36 Uhr schrieb Souham Biswas <
notifications@github.com>:
